### ISSUE TITLE
Feature Parser class file not supporting for Data tables

### ISSUE THREAD

**Issue by mred14** [sethijatin/cucumber-feature-distributor#1]

**Comment by sethijatin** [comment]
Thanks for notifying. Support for data tables will be included in the next release.

**Comment by sethijatin** [comment]
@mred14 : I have published a new release 1.3.1. Please update the release version in your POM.xml and validate the fix.

**Comment by mred14** [comment]
This is superb!, I appreciate you getting this to me so quickly and Thanks, this is exactly what I was looking for.
